import { Injectable } from '@angular/core';
import { Book, BookStatus, LiteraryGenre } from '../book/models/book.model';

@Injectable({
  providedIn: 'root'
})
export class MockedService {

  readonly BOOKS: Book[] = [
    // tslint:disable
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
  ];

  readonly USER_BOOKS: Book[] = [
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
    {id: '1', owner: 'John Doe Owner', status: BookStatus.Public, title: 'SomeTitle', author: 'John Doe Author', category: LiteraryGenre.Fiction, releaseDate: '11-11-2011', creationDate: '12-11-2020', description: 'Books description goes brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'},
  ]

  constructor() { }

  get books() {
    return this.BOOKS;
  }

  get userBooks() {
    return this.USER_BOOKS;
  }

}
